# Generated by Django 5.0.6 on 2024-08-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sagamdharamshala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phoneno', models.IntegerField()),
                ('roomno', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('filetp', models.FileField(default=None, max_length=250, null=True, upload_to='Sagamdharamshala/')),
            ],
        ),
    ]
