# Generated by Django 5.0.6 on 2024-09-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary',
            name='programme',
            field=models.TextField(max_length=500),
        ),
    ]
