# Generated by Django 5.0.6 on 2024-08-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sagamdharamshala', '0002_alter_sagamdharamshala_filetp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sagamdharamshala',
            name='filetp',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Sagamdharamshala/'),
        ),
    ]
