# Generated by Django 5.0.6 on 2024-09-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sagamdharamshala', '0003_alter_sagamdharamshala_filetp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sagamdharamshala',
            name='phoneno',
            field=models.IntegerField(max_length=20),
        ),
    ]
